travis:
  secure:
    BINSTAR_TOKEN: gvhffdkf7846egCWeec+pXA9CSjKmt1txE/Jwum1lmY+WU4iGGya3GqnqYx6c3+6AstmOHac5EsyaTrnslvCiNsrdd0mwoYOyNGrbxeuRiUxw4hrH54FF3cuL7OiyCf75IZXkmDRVLhhwbnvzqmLFx+ziUCrt0iOjxqmC1RXkiEX21RejuF0vvzB6bqC1FN5rUEzApCJx4zLKHmAL2hWpw9Z8pWsxTNZF9hWd/IbWq/Ifd6lvqIzQisxEph2l3tWHLdx6aCtkzO2wafhPUSRB8bkv0VwO2pKYCaHZCUpDasOKMrTcBkofze3FI8yo6pvfN1Q9MVwZhuQAwY/YXx6KpsZyeJSuYWhb1ccqFjZ0P+qLa65MSqpPJHFJzMluk766Jmv3dS+eqg5aZkho/MVKfREINjLizmcH9zn5yHwojEgPW9YYbNK8h7Y9HW2jCHyFlORlOJcTqt785dh5nL4oj13o6gVsVm/o5oBsaLWouMJmRlAPOPyw2fIVwTciNXV6kSPPCLvp9e1ZasFsQAtfV2Pe+dOwlYrfopgTwEGMOEiB9ew8mFKCzQc01JnTtDc+UzQcVDEcsTLFBldBhjLgLbb64FSXBt4+5C5yQAC9WzO1aJpJbmJEWnG9Cpy7lagTrwwHxyIXpbKYBGZM6Do9OgI3rJ3EEakUHx6+fLPMA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
